"""empty message

Revision ID: 5233d87d1d68
Revises: 793771937c1a
Create Date: 2024-04-29 21:55:45.513208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5233d87d1d68'
down_revision = '793771937c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
