"""empty message

Revision ID: 78a09d3fed05
Revises: b4ae6aa0368e
Create Date: 2024-04-28 15:33:49.090235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a09d3fed05'
down_revision = 'b4ae6aa0368e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_hora', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('fecha_hora')

    # ### end Alembic commands ###
