"""empty message

Revision ID: 793771937c1a
Revises: 78a09d3fed05
Create Date: 2024-04-29 21:53:52.091995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793771937c1a'
down_revision = '78a09d3fed05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
