"""Quitar comprobante de pago

Revision ID: 8482e599648c
Revises: c8eb73995588
Create Date: 2024-04-28 12:12:48.449676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8482e599648c'
down_revision = 'c8eb73995588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('comprobante_pago')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprobante_pago', sa.VARCHAR(length=200), nullable=True))

    # ### end Alembic commands ###
