"""empty message

Revision ID: b4ae6aa0368e
Revises: 0ce1cad50072
Create Date: 2024-04-28 14:54:04.823259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4ae6aa0368e'
down_revision = '0ce1cad50072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('fecha_registro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
