"""Agregar columna comprobante_pago

Revision ID: c8eb73995588
Revises: ac8c012cc66d
Create Date: 2024-04-28 11:59:33.679340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8eb73995588'
down_revision = 'ac8c012cc66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comprobante_pago', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('comprobante_pago')

    # ### end Alembic commands ###
